name: todo_c7_mon
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  provider: ^6.0.4
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_database: ^10.0.8
  cloud_firestore: ^4.3.0
  intl: ^0.18.0
  slidable_button: ^2.0.0+1
  flutter_slidable: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0

dev_dependencies:

  flutter_test:
    sdk: flutter



flutter_native_splash:
  color: "#DFECDB"
  image: assets/logo.png
  color_dark: "#060E1E"
  image_dark: assets/logo.png



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"


flutter:



  uses-material-design: true


  assets:
    - assets/logo.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
